filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'

checks:
    php:
        excluded_dependencies:
            - atoum/atoum

coding_style:
    php:
        spaces:
            around_operators:
                multiplicative: false

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
        coverage:
            tests:
                override:
                    - command: export XDEBUG_MODE=coverage
                    - command: './vendor/bin/atoum -d tests/units/Recurrence'
                      coverage:
                          file: './var/code-coverage/recurrence.coverage.xml'
                          format: 'clover'