filter:
    paths:
        - 'src/*'
    excluded_paths:
            - 'tests/*'
            - 'vendor/*'

checks:
    php:
        excluded_dependencies:
            - atoum/atoum

coding_style:
    php:
        spaces:
            around_operators:
                multiplicative: false

build:
    tests:
        override:
            -
                command: './vendor/bin/atoum -d tests/units/Recurrence'
                coverage:
                    file: './var/code-coverage/recurrence.coverage.xml'
                    format: 'clover'
