name: Coninuous Integration

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        php-versions: [7.0, 7.1, 7.2, 7.3, 7.4]
    name: PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          tools: composer:v1

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run tests
        run: ./vendor/bin/atoum -d tests/units/Recurrence